name: Build and Update Changelog
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build Changelog
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@v2
      with:
        configuration: ".github/changelog-configuration.json"
